### ISSUE TITLE
異なるhostnameでサーバーを起動した時に失敗する

### ISSUE THREAD

**Issue by jyasukawa** [s9t-gtr/webserv#18]
- setup multiple servers with different hostname (use something like: curl --resolve example.com:80:127.0.0.1
http://example.com/)

この評価項目で失敗してしまう。
最後に内容記憶してるコミットversion2にcheckoutしたら問題なく動いたから、それ以降の変更が影響してるかも、、

**Comment by s9t-gtr** [comment]
ありがとう！原因わかったからすぐ治します
